#!/bin/bash

IFS=' '

totalAdditions=0
totalDeletions=0
totalCommits=$(git rev-list --count HEAD)

while read lineStat
do
	read -a stats <<< $(echo $lineStat | sed -r 's/[^0-9 ]*//g')
	totalAdditions=$((totalAdditions + stats[1]))
	totalDeletions=$((totalDeletions + stats[2]))
done <<< $(git log --shortstat --format="%N" | sed -r "/^ *\t*$/d")

while read line
do
	author=$(echo $line | sed -r "s/^ *[0-9]*\t* *//")
	commits=$(echo $line | grep -o "^[0-9]*")

	additions=0
	deletions=0

	while read lineStat
	do
		read -a stats <<< $(echo $lineStat | sed -r 's/[^0-9 ]*//g')
		additions=$((additions + stats[1]))
		deletions=$((deletions + stats[2]))
	done <<< $(git log --author="$author" --shortstat --format="%N" | sed -r "/^ *\t*$/d")

	echo "$author $commits commits +$additions -$deletions"
done <<< $(git shortlog -se)

echo ""
echo "Total : $totalCommits commits +$totalAdditions -$totalDeletions"
